config/routes.rb
FoodieNote::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  get "search/create"
  get "locu_database_manager/update"

  root 'welcome#index'

  resources :restaurant
  resources :menu_item
  resources :comment
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include DateTimeModule

  belongs_to :menu_item
  belongs_to :user
  has_one :rating

  def get_date_created
  	return comment_format(date_created)
  end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  letsrate_rateable "taste", "quantity", "waiting_time"
  belongs_to :restaurant
  has_many :comments

  def isDuplicate
	menuItems = MenuItem.where(:locu_id => self.locu_id)
	if menuItems.count == 0
		return false
	else
		return true
	end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :menu_items

  def isDuplicate
  	restaurant = Restaurant.where(:locu_id => self.locu_id)
	if restaurant.count == 0
		return false
	else
		return true
	end
  end

  def self.getVenueFromLocu(locuID)
	venueSearchResult = HTTParty.get("https://api.locu.com/v1_0/venue/" + locuID + "/?api_key=007462acbbeebff0b661f26e36a26eef5eff36c4")
	venue = venueSearchResult["objects"][0]
	return venue;
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	#before_action :authenticate_user!
	def new
	end

	def create
		@menu_item = MenuItem.find_by_locu_id(params[:menu_item_id])
		@comment = @menu_item.comments.build(comments_param)
		@comment.date_created = DateTime.now
		#@comment.user = current_user
		@comment.save
		redirect_to menu_item_path(@menu_item)
	end

	def destroy
		@menu_item = MenuItem.find(params[:menu_item_id])
		@comment = @menu_item.comments.find(params[:id])
		@comment.destroy
		redirect_to restaurant_menu_item_path(@menu_item)
	end

	private
	def comments_param
		params[:comment].permit(:title,:body)
	end
end

app/controllers/menu_item_controller.rb
class MenuItemController < ApplicationController
	def new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@menu_item = @restaurant.menu_items.create(params[:menu_item]).permit(menu_item_params)
	end
	
	def index
	end

	def show
		@menu_item = MenuItem.find(params[:id])
		@restaurant = Restaurant.find(@menu_item.restaurant_id)
		@review_type = params[:review_type]
		if @review_type.nil?
			@review_type = "all"
		end
		@reviewtype_index = params[:index]
		if @reviewtype_index.nil?
			@reviewtype_index = "0";
		end
	end

	def update
		review_type = params[:menu_item][:review_types]
		if review_type.nil?
			#redirect_to menu_item_path(@menu_item)
		end
		@menu_item = MenuItem.find(params[:id])
		if @menu_item.review_types.nil?
			@menu_item.review_types = review_type
		else
			@menu_item.review_types += "," + review_type
		end
		@menu_item.save;
		redirect_to menu_item_path(@menu_item)
	end

	private
	def menu_item_params
		params.require(:menu_item).permit(:locu_id, :name, :description,:price, :restaurant_id)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
	def new
	end

	def create
		@restaurant = Restaurant.new(restauarant_params)
	end

	def index
		@restaurants = Restaurant.all
		@query = params[:query]
		url = "https://api.locu.com/v2/venue/search"
		@response = HTTParty.post(url,
			     :body => { :api_key => "007462acbbeebff0b661f26e36a26eef5eff36c4", "venue_queries" => [{:name => @query}]}.to_json,
			     :headers => { 'Content-Type' => 'application/json' })
		
	end
	
	def show
		@restaurant = Restaurant.find(params[:id])
	end

	private
	def restaurant_params
		params.require(:restaurant).permit(:locu_id, :name)
	end
end

app/controllers/reviewtype_controller.rb
class ReviewtypeController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def create
		zipcode = params[:search]['zipcode']
		redirect_to restaurant_index_path(:query => params[:search]['query'], :zipcode => zipcode)
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  @query = params['query']
	  @zipcode = params['zipcode']
	  if @query.nil? || @query == ""
		  @query = '';
		  @restaurants = []
		  return
	  end
	  if @zipcode.nil?
	  	@zipcode = '';
	  end

	  search_condition = "%" + @query + "%"
	  zipcode_condition = @zipcode
	  zipcode_condition.gsub! 'Current Location - ', ''
	  @restaurants = Restaurant.find(:all, :conditions => ['name LIKE ? AND postal_code = ?', search_condition, zipcode_condition]);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviewtype_helper.rb
module ReviewtypeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/_form.html.erb
<%= javascript_include_tag "comment" %>
<%= stylesheet_link_tag "comment" %>
<div class="review_wrapper">
<div class="review_header">
	<div class="review_header_left">
		<div class="camera_icon"></div>
	</div>
	<div class="review_header_right">
		<div class="review_header_menuitem_name">
			<%= @menu_item.name %>
		</div>
		<div class="review_header_rating">
			<img src="/assets/star-on.png">
			<img src="/assets/star-on.png">
			<img src="/assets/star-on.png">
			<img src="/assets/star-on.png">
			<img src="/assets/star-off.png"> &nbsp;&nbsp;"It was great"
		</div>
	</div>
</div>
<div class="review_content">
	<%= form_for :comment, url: comment_index_path(params.merge(:menu_item_id => @menu_item.locu_id)) do |f| %>
		<%= f.text_area :title, :class=>"review_body", :id=>"review_content_title", :maxlength => 150%>
		<div id="review_content_title_counter" class="review_counter"></div>
		<%= f.text_area :body, :class=>"review_body", :id=>"review_content_body", :maxlength => 500 %>
		<div id="review_content_body_counter" class="review_counter"></div>
	<div class="review_submit" align="center">
		<%= f.submit "Post a review" %>
	</div>
</div>
<% end %>

</div>

app/views/comment/_list.html.erb
<%- @menu_item.comments.order(:date_created).reverse_order.each do |comment| %>
	<%- #next if comment.user.nil? %>
	<div class="review_content_row">
		<div class="review_content_left">
			<%= comment.title %>
		</div>
		<div class="review_content_right">
			<%= comment.get_date_created() %>
		</div>
	</div>
	<% if @review_type == "tips" %>
	<div class="review_content_row">
		<div class="review_content_body">
			<%= comment.body %>
		</div>
	</div>
	<% end %>
<% end %>

app/views/comment/comment.js.erb
$("#write_review").prepend('<%= escape_javascript(render 'comment/new') %>');

app/views/comment/create.html.erb
<%= @params %>
<%= @params.each do |key, value| %>
	<%= key + " = " + value %>
<% end %>

app/views/comment/new.html.erb
<%= stylesheet_link_tag "comment" %>
<%= form_for :comment, url: comment_index_path(params.merge(:menu_item_id => @menu_item.locu_id)) do |f| %>
<div class="review_wrapper">
	<div class="review_header">
		<div class="rating">
			<%= rating_for @menu_item, "quantity" %>
		</div>
	</div>
	<div class="review_content">
		<%= f.text_area :body, :class=>"review_body" %>
		<%= f.submit :class=>"review_submit" %></td>
	</div>
</div>
<% end %>

app/views/comment/new.js.erb
$("<%= escape_javascript(render 'comment/form') %>").appendTo("#write_review");

app/views/menu_item/_form.html.erb
<%= javascript_include_tag "menu_item" %>
<%= stylesheet_link_tag "menu_item" %>
<div class="menuitem_wrapper">
	<div class="menuitem_detail_wrapper">
		<div class="menuitem_detail_left">
			<strong><%= @menu_item.name %></strong>
			<div class="menuitem_rating">
				4.1 <img src='/assets/star-on.png'>
				<img src='/assets/star-on.png'>
				<img src='/assets/star-on.png'>
				<img src='/assets/star-on.png'>
				<img src='/assets/star-off.png'>
				&nbsp;&nbsp;&nbsp;<span style="font-size:0.7em;">23,252 reviews</span>
			</div>
		</div>
		<div class="menuitem_detail_right">
			<div class="menuitem_price">$22</div>
			<div class="menuitem_write_link">
				Write a review
			</div>
		</div>
	</div>	
	<div class="menuitem_picture"></div>
	<div class="reviewtypes_wrapper">
	</div>
		
	<div class="review_content_wrapper">
		<table>
	<%- @menu_item.comments.order(:date_created).reverse_order.each do |comment| %>
	<%- next if comment.user.nil? %>
	<tr>
		<td><%= rating_for_user @menu_item, comment.user, "quantity" %>
		<td><%= comment.user.email %></td>
		<td><%= comment.body %></td>
	<td><%= comment.get_date_created() %></td>
	</tr>
<% end %>
</table>
	</div>
</div>

<%= link_to 'Back to Menu List', restaurant_path(@restaurant) %>

app/views/menu_item/show.html.erb
<%= stylesheet_link_tag "menu_item" %>
<div class="write_review_wrapper" style="display:none;">
	<%= render 'comment/form' %>
</div>
<div class="menuitem_wrapper" style="display:block;">
	<div class="menuitem_detail_wrapper">
		<div class="menuitem_detail_left">
			<strong><%= @menu_item.name %></strong>
			<div class="menuitem_rating">
				4.1 <img src='/assets/star-on.png'>
				<img src='/assets/star-on.png'>
				<img src='/assets/star-on.png'>
				<img src='/assets/star-on.png'>
				<img src='/assets/star-off.png'>
				&nbsp;&nbsp;&nbsp;<span style="font-size:0.7em;">23,252 reviews</span>
			</div>
		</div>
		<div class="menuitem_detail_right">
			<div class="menuitem_price">$22</div>
			<div class="menuitem_write_link">
				<a href="#" onclick="showWriteReviewWrapper()">Write a review</a>
			</div>
		</div>
	</div>	
	<div class="menuitem_picture"></div>
	<div align="center" class="reviewtypes_wrapper">
		<%= render 'reviewtype/index' %>
	</div>
	<div class="review_best_wrapper" id="review_best_wrapper<%= @reviewtype_index %>">
	</div>
	<div class="review_content_wrapper">
		<%= render 'comment/list' %>
	</div>
</div>

<%= link_to 'Back to Menu List', restaurant_path(@restaurant) %>

<BR>
<h1>Review Types:</h1>
<%= form_for @menu_item do |f| %>
	<%= f.text_field :review_types, :value => ''%>
	<%= f.submit "Add" %>
<% end %>

app/views/menu_item/update.html.erb
menuitem update?

app/views/restaurant/index.html.erb
<h1>Listing Restaurants</h1>
<% @restaurants.each do |restaurant| %>
	<%= link_to restaurant.name, restaurant_path(restaurant) %><BR>
<% end %>
<% if @query.nil? || @query == "" %>
<%= "hello"%>
<% else %>
<%= "Search for " + @query %>
<% end %>

app/views/restaurant/show.html.erb
<%= stylesheet_link_tag "restaurant" %>
<div class="restaurant_info_wrapper"> 
	<div class="restaurant_name"><%= @restaurant.name.upcase %></div>
	<div class="restaurant_address"><%= @restaurant.region %></div>
</div>
<div class="restaurant_menu_wrapper">
	<div class="restaurant_submenu_wrapper">
		<P>BEST OF BEST(6)</P>
		<P>DINNER(16)</P>
		<P>BRUNCH(12)</P>
		<P>LUNCH(20)</P>
		<P>APPETIZER(16)</P>
		<P>DRINK(13)</P>
		<P>DESSERT(15)</P>
	</div>
	<div class="restaurant_menuitem_wrapper">
		<% @restaurant.menu_items.each do |menu_item| %>
			<%= link_to menu_item_path(menu_item.id) do %>
			<div class="restaurant_menuitems">
				<div class="restaurant_menuitems_image"></div>
				<div class="restaurant_menuitems_info"><%= menu_item.name %></div>
			</div>
			<% end %>
		<% end %>
	</div>
</div>
<%= link_to 'Back', restaurant_index_path %>

app/views/user/_form.html.erb
<% if user_signed_in? %>
	Signed in as <%= current_user.email %>. Not you?
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
	<%= link_to "Log In", new_user_session_path, :class => "user_login" %><%= link_to "Sign Up", new_user_registration_path, :class => "user_signup" %>
<% end %>