config/routes.rb
FoodieNote::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  get "search/create"
  get "locu_database_manager/update"

  root 'welcome#index'

  resources :restaurant
  resources :menu_item
  resources :comment
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include DateTimeModule

  belongs_to :menu_item
  belongs_to :user
  has_one :rating

  def get_date_created
  	return comment_format(date_created)
  end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  letsrate_rateable "taste", "quantity", "waiting_time"
  belongs_to :restaurant
  has_many :comments

  def isDuplicate
	menuItems = MenuItem.where(:locu_id => self.locu_id)
	if menuItems.count == 0
		return false
	else
		return true
	end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :menu_items

  def isDuplicate
  	restaurant = Restaurant.where(:locu_id => self.locu_id)
	if restaurant.count == 0
		return false
	else
		return true
	end
  end

  def self.getVenueFromLocu(locuID)
	venueSearchResult = HTTParty.get("https://api.locu.com/v1_0/venue/" + locuID + "/?api_key=007462acbbeebff0b661f26e36a26eef5eff36c4")
	venue = venueSearchResult["objects"][0]
	return venue;
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	#before_action :authenticate_user!
	def new
	end

	def create
		@menu_item = MenuItem.find_by_locu_id(params[:menu_item_id])
		@comment = @menu_item.comments.build(comments_param)
		@comment.date_created = DateTime.now
		#@comment.user = current_user
		@comment.save
		redirect_to menu_item_path(@menu_item)
	end

	def destroy
		@menu_item = MenuItem.find(params[:menu_item_id])
		@comment = @menu_item.comments.find(params[:id])
		@comment.destroy
		redirect_to restaurant_menu_item_path(@menu_item)
	end

	private
	def comments_param
		params[:comment].permit(:title,:body)
	end
end

app/controllers/menu_item_controller.rb
class MenuItemController < ApplicationController
	def new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@menu_item = @restaurant.menu_items.create(params[:menu_item]).permit(menu_item_params)
	end
	
	def index
	end

	def show
		@menu_item = MenuItem.find(params[:id])
		@restaurant = Restaurant.find(@menu_item.restaurant_id)
		@review_type = params[:review_type]
		if @review_type.nil?
			@review_type = "all"
		end
		@reviewtype_index = params[:index]
		if @reviewtype_index.nil?
			@reviewtype_index = "0";
		end
	end

	def update
		review_type = params[:menu_item][:review_types]
		if review_type.nil?
			#redirect_to menu_item_path(@menu_item)
		end
		@menu_item = MenuItem.find(params[:id])
		if @menu_item.review_types.nil?
			@menu_item.review_types = review_type
		else
			@menu_item.review_types += "," + review_type
		end
		@menu_item.save;
		redirect_to menu_item_path(@menu_item)
	end

	private
	def menu_item_params
		params.require(:menu_item).permit(:locu_id, :name, :description,:price, :restaurant_id)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
	def new
	end

	def create
		@restaurant = Restaurant.new(restauarant_params)
	end

	def index
		@restaurants = Restaurant.all
		@query = params[:query]
		url = "https://api.locu.com/v2/venue/search"
		@response = HTTParty.post(url,
			     :body => { :api_key => "007462acbbeebff0b661f26e36a26eef5eff36c4", "venue_queries" => [{:name => @query}]}.to_json,
			     :headers => { 'Content-Type' => 'application/json' })
		
	end
	
	def show
		@restaurant = Restaurant.find(params[:id])
	end

	private
	def restaurant_params
		params.require(:restaurant).permit(:locu_id, :name)
	end
end

app/controllers/reviewtype_controller.rb
class ReviewtypeController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def create
		zipcode = params[:search]['zipcode']
		redirect_to restaurant_index_path(:query => params[:search]['query'], :zipcode => zipcode)
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  @query = params['query']
	  @zipcode = params['zipcode']
	  if @query.nil? || @query == ""
		  @query = '';
		  @restaurants = []
		  return
	  end
	  if @zipcode.nil?
	  	@zipcode = '';
	  end

	  search_condition = "%" + @query + "%"
	  zipcode_condition = @zipcode
	  zipcode_condition.gsub! 'Current Location - ', ''
	  @restaurants = Restaurant.find(:all, :conditions => ['name LIKE ? AND postal_code = ?', search_condition, zipcode_condition]);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviewtype_helper.rb
module ReviewtypeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reviewtype/_index.html.erb
<%= javascript_include_tag "reviewtype" %>
<div class="reviewtypes_clip_container">
	<%= link_to '?review_type=all&index=0' do %>
		<img id="reviewtype0_bigger" class="reviewtype_bigger" src="/assets/reviewtype0bigger.png">
		<img id="reviewtype0"  class="reviewtype_icons" src="/assets/reviewtype0.png">
	<% end %>
</div>
<div class="reviewtypes_clip_container">
	<%= link_to '?review_type=tips&index=1' do %>
		<img id="reviewtype1_bigger"  class="reviewtype_icons" src="/assets/reviewtype1.png">
		<img id="reviewtype1" class="reviewtype_bigger" src="/assets/reviewtype1bigger.png">
	<% end %>
</div>
<% if @menu_item.review_types %>
	<% review_types = @menu_item.review_types.split(",") %>
	<% review_types.each_with_index do |review_type, index| %>
		<% next if (index>3) %>
		<% nameIndex = (index + 2).to_s %>
		<div class="reviewtypes_clip_container">
			<%= link_to '?review_type='+review_type+'&index='+ nameIndex do %>
				<img id="reviewtype<%= nameIndex %>_bigger" class="reviewtype_bigger" src="/assets/reviewtype<%= nameIndex %>bigger.png">
				<img id="reviewtype<%= nameIndex %>" class="reviewtype_icons" src="/assets/reviewtype<%= nameIndex %>.png">
				<p class="reviewtypes_clip_text" id="reviewtypes_clip_text<%= nameIndex %>">
					<%= review_type.upcase %>
				</p>
			<% end %>
		</div>
	<% end %>
<% end %>

app/views/search/_form.html.erb
<%= form_for :search, url: search_create_path, html: { :method => 'GET' } do |f| %>
	<%= f.text_field :query, :id => "search_query", :placeholder=> "Find Restaurant", :value => @query %>&nbsp;&nbsp;&nbsp;
	<%= f.text_field :zipcode, :placeholder => "Zipcode", :id => "search_zipcode", :value => @zipcode %>
	<%= f.submit 'search', :class => "search_submit" %>
<% end %>

app/views/welcome/index.html.erb
<%= @query %>
<%= @geocode %>
<h2>Restaurants</h2>
<% @restaurants.each do |restaurant| %>
	<%= link_to restaurant.name, restaurant_path(restaurant) %><BR>
<% end %>

<h2>Link</h2>
<%= link_to "Restaurants", controller: "restaurant" %><br/>
<%= link_to "Update Restaurant", locu_database_manager_update_path %>